# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opinion_analyzer.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'opinion_analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16opinion_analyzer.proto\x12\x07opinion\":\n\x0e\x41nalyzeRequest\x12\x12\n\ntopic_text\x18\x01 \x01(\t\x12\x14\n\x0copinion_text\x18\x02 \x01(\t\"*\n\x0f\x41nalyzeResponse\x12\x17\n\x0f\x61nalysis_result\x18\x01 \x01(\t2_\n\x16OpinionAnalyzerService\x12\x45\n\x0e\x41nalyzeOpinion\x12\x17.opinion.AnalyzeRequest\x1a\x18.opinion.AnalyzeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opinion_analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEREQUEST']._serialized_start=35
  _globals['_ANALYZEREQUEST']._serialized_end=93
  _globals['_ANALYZERESPONSE']._serialized_start=95
  _globals['_ANALYZERESPONSE']._serialized_end=137
  _globals['_OPINIONANALYZERSERVICE']._serialized_start=139
  _globals['_OPINIONANALYZERSERVICE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
